@Reveries_Https = https://localhost:7238
@Reveries_Http = http://localhost:5023

###
GET {{Reveries_Https}}/api/Test/ping/
Accept: application/json

### Swagger
GET {{Reveries_Https}}/swagger/v1/swagger.json
Accept: application/json

### Get Book
GET {{Reveries_Https}}/api/v1/Books/9780316539883
Accept: application/json

### Get All Books
GET {{Reveries_Https}}/api/v1/Books

### Get All Read Books
GET {{Reveries_Https}}/api/v1/Books?isRead=true