events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;
        server_name raspberrypi;
        return 301 https://$host$request_uri;
    }
    
    server {
        listen 443 ssl;
        server_name raspberrypi;

        ssl_certificate /etc/nginx/certs/cert.crt;
        ssl_certificate_key /etc/nginx/certs/cert.key;
        
        # Bookscanner: raspberrypi/scanner -> :8081
        location /app/ {
            proxy_pass http://bookscanner:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # API: raspberrypi/api -> :8080
        location /api {
            proxy_pass http://api:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Grafana: raspberrypi/grafana -> :3000
        location /grafana {
            proxy_pass http://grafana:3000;
            proxy_set_header Host $host;
        }
    }
}