global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus selv
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Node Exporter (Raspberry Pi metrics)
  - job_name: 'raspberry-pi'
    static_configs:
      - targets: ['host.docker.internal:9100']
        labels:
          instance: 'raspberrypi'
  
  # Scrape PostgreSQL Exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']